#!/bin/bash

CONFFILE="/etc/cdrlogs.conf"

function getconf {
  cat $CONFFILE | grep $1 | gawk -F= '{ print $2 }'
}

CDR_LOGFILE=`getconf LOGFILE`
CDR_MYSQL="mysql -Dcdrlogs -s"
CDR_PIDFILE="/tmp/$PROCNAME.pid"
CDR_WORKDIR=`getconf WORKDIR`

function dolog {
  echo "`date` - $PROCNAME - $1" >> $CDR_LOGFILE
}

function checklock {
  PID=`cat $CDR_PIDFILE`
  PIDCNT=`ps -ef | grep $PID | grep -v grep | wc -l`
  if [ $PIDCNT -eq 0 ]; then
    dolog "Lock file appears to be dead deleting to move on"
    rm -rf $CDR_PIDFILE ; dolog "Deleted $CDR_PIDFILE for PID $PID"
  fi
}

function checkrun {
  if [ -f $CDR_PIDFILE ]; then
    checklock ; dolog "Exiting already running" ; exit 2
  else
    echo $$ > $CDR_PIDFILE
  fi
}

function checksql {
  sqlup=`echo "show status" | mysql | grep Uptime | grep -v since | gawk '{ print $2 }'`

  if [ $sqlup -lt 300 ]; then
    exit 3
  fi
}

export CDR_LOGFILE CDR_MYSQL CDR_PIDFILE

